/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.example.app.Persona
import org.example.app.Fecha

fun main() {
    println(Persona("pepe", "honguito", Fecha(5, 6, 2026)))
}
